### ISSUE TITLE
Protocol  sequence error.

### ISSUE THREAD

**Issue by rdebath** [yourfriendoss/Cla55ic#3]
It appears you're sending a "Server identification" packet first.
This is not correct, the sequence should be:
1) Client sends identification packet (Server may respond with 0xE disconnect)
2) If Client does NOT have 0x42 flag jump to step (5) and disable all extensions.
3) Server sends Extinfo and Extentry Packets
4) Client sends Extinfo and Extentry packets
5) Server sends Identification packet.

**Comment by yourfriendoss** [comment]
UnknownShadow200+ - the classicube client doesn't care when a handshake packet is sent

As it seems, this doesn't really matter.
