### ISSUE TITLE
What is the client version that Cla55ic support

### ISSUE THREAD

**Issue by codingwatching** [yourfriendoss/Cla55ic#4]
Hi @yourfriendoss 
How I can find the client version that is supported by Cla55ic?
Could you please hint me the name of the client to download and play with Cla55ic?
Thank you so much!

**Comment by yourfriendoss** [comment]
ClassiCube! Once you download ClassiCube, create a account and log in, you should be able to find Cla55ic in the multiplayer serverlist! 

Thank you for your intrest in cla55ic!
