### ISSUE TITLE
How to custom world loading (Create new custom world)

### ISSUE THREAD

**Issue by codingwatching** [yourfriendoss/Cla55ic#5]
Hi @yourfriendoss 
Follow up on your latest comment, I can  now use the ClassiCube client and find your server
How to create a custom world like the house in the current live server?
I just a newbie in Minecraft server so I am sorry if I asking some too common question
It is great if we have some tutorial or link on how to create and custom a world for this server
Thank you!

**Comment by yourfriendoss** [comment]
Hey! What's your username? Also, I never had a custom world system before this, and now I just pushed one! Use `/createworld name` to create a world, and use `/go name` to go to that world!
